github.com:
    users:
        wangsijie:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: wangsijie
