import { useCallback, useEffect, useState, type FormEvent } from 'react';
import {
  fetchChanges,
  publishChanges,
  type PublishResult,
  type SessionChanges
} from '../api';

const STATUS_LABELS: Record<string, string> = {
  added: 'added',
  modified: 'modified',
  deleted: 'deleted',
  renamed: 'renamed',
  untracked: 'untracked',
  conflicted: 'conflicted'
};

/**
 * What the agent changed, and the way out of the container.
 *
 * This is the panel that makes a session's output reviewable without leaving
 * the conversation: the file list and diff come from git in the checkout, and
 * publishing commits, pushes and (optionally) opens a pull request in one step.
 *
 * It loads on demand rather than with the page. Reading a diff runs commands in
 * the container, so paying for it on every session view — and on every poll —
 * would make looking at a conversation more expensive than having one.
 */
export function ChangesPanel({
  sessionId,
  attached,
  sessionTitle
}: {
  sessionId: string;
  attached: boolean;
  sessionTitle: string;
}) {
  const [open, setOpen] = useState(false);
  const [changes, setChanges] = useState<SessionChanges>();
  const [error, setError] = useState<string>();
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [withPullRequest, setWithPullRequest] = useState(true);
  const [published, setPublished] = useState<PublishResult>();

  const load = useCallback(async () => {
    setLoading(true);
    setError(undefined);
    try {
      setChanges(await fetchChanges(sessionId));
    } catch (cause) {
      setChanges(undefined);
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setLoading(false);
    }
  }, [sessionId]);

  // Opening is the request to read; a sleeping container has nothing to read
  // and must not be woken by a panel being expanded.
  useEffect(() => {
    if (open && attached && !changes && !loading) {
      void load();
    }
  }, [open, attached, changes, loading, load]);

  async function publish(event: FormEvent) {
    event.preventDefault();
    const commitMessage = message.trim() || sessionTitle;
    if (!commitMessage || busy) {
      return;
    }
    setBusy(true);
    setError(undefined);
    try {
      const result = await publishChanges(sessionId, {
        message: commitMessage,
        ...(withPullRequest
          ? {
              pullRequest: {
                title: commitMessage.split('\n')[0],
                body: `Generated by OpenCode Cloud session ${sessionId}.`
              }
            }
          : {})
      });
      setPublished(result);
      setMessage('');
      await load();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      setBusy(false);
    }
  }

  const dirty = (changes?.files.length ?? 0) > 0;
  const canPublish = dirty || (changes?.unpushedCommits ?? 0) > 0;

  return (
    <section className="card changes-panel">
      <header className="changes-header">
        <button
          className="link-button"
          type="button"
          onClick={() => setOpen((value) => !value)}
          aria-expanded={open}
        >
          {open ? '▾' : '▸'} Changes
        </button>
        {open && attached ? (
          <button
            className="link-button"
            type="button"
            disabled={loading || busy}
            onClick={() => void load()}
          >
            Refresh
          </button>
        ) : null}
      </header>

      {!open ? null : !attached ? (
        <p className="muted">
          This session is asleep. Send a message to wake the container, then the
          changes show up here.
        </p>
      ) : loading && !changes ? (
        <p className="muted">Reading the workspace…</p>
      ) : (
        <>
          {changes ? (
            <>
              <p className="muted mono">
                {changes.branch}
                {changes.onDefaultBranch ? ' (default branch)' : ''} ·{' '}
                {changes.files.length} files
                {changes.unpushedCommits > 0
                  ? ` · ${changes.unpushedCommits} unpushed commits`
                  : ''}
              </p>
              {changes.files.length > 0 ? (
                <ul className="changed-files">
                  {changes.files.map((file) => (
                    <li key={file.path}>
                      <span className={`file-status status-${file.status}`}>
                        {STATUS_LABELS[file.status] ?? file.status}
                      </span>
                      <span className="mono">
                        {file.renamedFrom ? `${file.renamedFrom} → ` : ''}
                        {file.path}
                      </span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="muted">Working tree is clean — nothing uncommitted.</p>
              )}
              {changes.diff ? (
                <details className="diff-view">
                  <summary>View diff</summary>
                  <pre className="diff mono">{changes.diff}</pre>
                  {changes.diffTruncated ? (
                    <p className="muted">
                      Diff was too long and got truncated; run git diff in the
                      workspace terminal for the full text.
                    </p>
                  ) : null}
                </details>
              ) : null}
              {/*
                Untracked files have no diff against HEAD, and showing one would
                mean staging them during a read. Saying so beats a file list the
                diff silently disagrees with.
              */}
              {changes.files.some((file) => file.status === 'untracked') ? (
                <p className="muted">
                  New (untracked) files are not in the diff, but they are
                  committed along with everything else.
                </p>
              ) : null}
            </>
          ) : null}

          {error ? (
            <p className="banner error" role="alert">
              {error}
            </p>
          ) : null}

          {published ? (
            <p className="banner">
              Pushed to <span className="mono">{published.branch}</span>
              {published.nothingToCommit
                ? ' (working tree was already clean; pushed earlier commits)'
                : ''}
              {published.pullRequestUrl ? (
                <>
                  {' · '}
                  <a href={published.pullRequestUrl} target="_blank" rel="noreferrer">
                    View PR ↗
                  </a>
                </>
              ) : null}
            </p>
          ) : null}

          {changes ? (
            <form className="publish-form" onSubmit={publish} aria-busy={busy}>
              <textarea
                className="prompt"
                rows={2}
                placeholder="Commit message (defaults to the session title)"
                value={message}
                disabled={busy || !canPublish}
                onChange={(event) => setMessage(event.target.value)}
              />
              <div className="composer-controls">
                <label className="checkbox">
                  <input
                    type="checkbox"
                    checked={withPullRequest}
                    disabled={busy || !canPublish}
                    onChange={(event) => setWithPullRequest(event.target.checked)}
                  />
                  Open a PR too
                </label>
                <button
                  className="button primary"
                  type="submit"
                  disabled={busy || !canPublish}
                >
                  Commit and push to {changes.publishBranch}
                </button>
              </div>
              {changes.onDefaultBranch ? (
                <p className="muted">
                  Changes move to <span className="mono">{changes.publishBranch}</span>{' '}
                  first — nothing is committed straight to {changes.defaultBranch}.
                </p>
              ) : null}
            </form>
          ) : null}
        </>
      )}
    </section>
  );
}
